### ISSUE TITLE
Add operations to the t_elist linked list

### ISSUE THREAD

**Issue by gabrielclcardoso** [raytracers/miniRT#29]
#### The following operatios should be added:
* add_back()
* lst_new()
* free_lst()

**Comment by Leofariasrj25** [comment]
Do you pretend to implement them like the libft version or do you have something else planned?

**Comment by gabrielclcardoso** [comment]
> Do you pretend to implement them like the libft version or do you have something else planned?

the add_back() and lst_new() will be pretty similar, but I inted to use pointer to functions inside the lst_new.
